// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity playerGameObject;
            [FieldOffset(4)]
            public Vector3 localPos;
        }

        public static unsafe _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 16) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for command with ID 6");
            }

            var orig = new _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64();
            var comp = (Interop*)data;
            orig.playerGameObject = comp->playerGameObject;
            orig.localPos = comp->localPos;
            return orig;
        }

        public Entity playerGameObject;
        public Vector3 localPos;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 6;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(playerGameObject, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.playerGameObject = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(playerGameObject, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.playerGameObject = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.playerGameObject,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.playerGameObject == entity) {
                this.playerGameObject = Entity.InvalidRelative;
            }
        }
        
        public _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(
        Entity entity,
        Entity playerGameObject,
        Vector3 localPos
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.playerGameObject = playerGameObject; 
            this.localPos = localPos; 
        }
        
        public static void Serialize(_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.playerGameObject);
            var converted_localPos = commandData.localPos.ToCoreVector3();
            bitStream.WriteVector3(converted_localPos, FloatMeta.NoCompression());
        }
        
        public static _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataplayerGameObject = bitStream.ReadEntity();
            var converted_localPos = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datalocalPos = converted_localPos.ToUnityVector3();
    
            return new _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64()
            {
                Entity = entity,
                Routing = target,
                playerGameObject = dataplayerGameObject,
                localPos = datalocalPos
            };   
        }
    }

}
