// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _006c748d7f8085f4691d554734b27fe0_8362810714748207749 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity networkedCurrentFieldTransform;
            [FieldOffset(4)]
            public System.Byte NetworkIsControlled;
            [FieldOffset(5)]
            public Entity ControllingPlayerGameObject;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8362810714748207749.networkedCurrentFieldTransformMask;
            networkedCurrentFieldTransformSimulationFrame = frame;
            FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8362810714748207749.NetworkIsControlledMask;
            NetworkIsControlledSimulationFrame = frame;
            FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8362810714748207749.ControllingPlayerGameObjectMask;
            ControllingPlayerGameObjectSimulationFrame = frame;
        }

        public static unsafe _006c748d7f8085f4691d554734b27fe0_8362810714748207749 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 9) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 9) " +
                    "for component with ID 20");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 20");
            }

            var orig = new _006c748d7f8085f4691d554734b27fe0_8362810714748207749();

            var comp = (Interop*)data;

            orig.networkedCurrentFieldTransform = comp->networkedCurrentFieldTransform;
            orig.NetworkIsControlled = comp->NetworkIsControlled != 0;
            orig.ControllingPlayerGameObject = comp->ControllingPlayerGameObject;

            return orig;
        }


        public static uint networkedCurrentFieldTransformMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame networkedCurrentFieldTransformSimulationFrame;
        public Entity networkedCurrentFieldTransform;
        public static uint NetworkIsControlledMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame NetworkIsControlledSimulationFrame;
        public System.Boolean NetworkIsControlled;
        public static uint ControllingPlayerGameObjectMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame ControllingPlayerGameObjectSimulationFrame;
        public Entity ControllingPlayerGameObject;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 20;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => true;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return new HashSet<Entity>()
            {
                this.networkedCurrentFieldTransform,
                this.ControllingPlayerGameObject,
            };
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            uint refsMask = 0;

            if (this.networkedCurrentFieldTransform == fromEntity)
            {
                this.networkedCurrentFieldTransform = toEntity;
                refsMask |= 1 << 0;
            }
            if (this.ControllingPlayerGameObject == fromEntity)
            {
                this.ControllingPlayerGameObject = toEntity;
                refsMask |= 1 << 2;
            }

            FieldsMask |= refsMask;

            return refsMask;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            Entity absoluteEntity;
            IEntityMapper.Error err;
            err = mapper.MapToAbsoluteEntity(this.networkedCurrentFieldTransform, false, out absoluteEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.networkedCurrentFieldTransform = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(this.ControllingPlayerGameObject, false, out absoluteEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.ControllingPlayerGameObject = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            Entity relativeEntity;
            IEntityMapper.Error err;
            // We assume that the inConnection held changes with unresolved references, so the 'createMapping=true' is
            // there only because there's a chance that the parent creation change will be processed after this one
            // meaning there's no mapping for the parent yet. This wouldn't be necessary if mapping creation would happen
            // in the clientWorld via create/destroy requests while here we would only check whether mapping exists or not.
            var createParentMapping_networkedCurrentFieldTransform = true;
            err = mapper.MapToRelativeEntity(this.networkedCurrentFieldTransform, createParentMapping_networkedCurrentFieldTransform,
             out relativeEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.networkedCurrentFieldTransform = relativeEntity;
            // We assume that the inConnection held changes with unresolved references, so the 'createMapping=true' is
            // there only because there's a chance that the parent creation change will be processed after this one
            // meaning there's no mapping for the parent yet. This wouldn't be necessary if mapping creation would happen
            // in the clientWorld via create/destroy requests while here we would only check whether mapping exists or not.
            var createParentMapping_ControllingPlayerGameObject = true;
            err = mapper.MapToRelativeEntity(this.ControllingPlayerGameObject, createParentMapping_ControllingPlayerGameObject,
             out relativeEntity);

            if (err != IEntityMapper.Error.None)
            {
                return err;
            }

            this.ControllingPlayerGameObject = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_006c748d7f8085f4691d554734b27fe0_8362810714748207749)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.networkedCurrentFieldTransformSimulationFrame = other.networkedCurrentFieldTransformSimulationFrame;
                this.networkedCurrentFieldTransform = other.networkedCurrentFieldTransform;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.NetworkIsControlledSimulationFrame = other.NetworkIsControlledSimulationFrame;
                this.NetworkIsControlled = other.NetworkIsControlled;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.ControllingPlayerGameObjectSimulationFrame = other.ControllingPlayerGameObjectSimulationFrame;
                this.ControllingPlayerGameObject = other.ControllingPlayerGameObject;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_006c748d7f8085f4691d554734b27fe0_8362810714748207749 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.networkedCurrentFieldTransform;



                bitStream.WriteEntity(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.NetworkIsControlled;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.ControllingPlayerGameObject;



                bitStream.WriteEntity(fieldValue);
            }

            mask >>= 1;

            return mask;
        }

        public static _006c748d7f8085f4691d554734b27fe0_8362810714748207749 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new _006c748d7f8085f4691d554734b27fe0_8362810714748207749();
            if (bitStream.ReadMask())
            {

                val.networkedCurrentFieldTransform = bitStream.ReadEntity();
                val.FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8362810714748207749.networkedCurrentFieldTransformMask;
            }
            if (bitStream.ReadMask())
            {

                val.NetworkIsControlled = bitStream.ReadBool();
                val.FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8362810714748207749.NetworkIsControlledMask;
            }
            if (bitStream.ReadMask())
            {

                val.ControllingPlayerGameObject = bitStream.ReadEntity();
                val.FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8362810714748207749.ControllingPlayerGameObjectMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_006c748d7f8085f4691d554734b27fe0_8362810714748207749(" +
                $" networkedCurrentFieldTransform: { this.networkedCurrentFieldTransform }" +
                $" NetworkIsControlled: { this.NetworkIsControlled }" +
                $" ControllingPlayerGameObject: { this.ControllingPlayerGameObject }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }

}
