// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray playerID;
            [FieldOffset(16)]
            public Vector3 localPos;
        }

        public static unsafe _006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 28) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 28) " +
                    "for command with ID 6");
            }

            var orig = new _006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7();
            var comp = (Interop*)data;
            orig.playerID = comp->playerID.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->playerID.Data, (int)comp->playerID.Length) : null;
            orig.localPos = comp->localPos;
            return orig;
        }

        public System.String playerID;
        public Vector3 localPos;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 6;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7(
        Entity entity,
        System.String playerID,
        Vector3 localPos
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.playerID = playerID; 
            this.localPos = localPos; 
        }
        
        public static void Serialize(_006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(commandData.playerID);
            var converted_localPos = commandData.localPos.ToCoreVector3();
            bitStream.WriteVector3(converted_localPos, FloatMeta.NoCompression());
        }
        
        public static _006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataplayerID = bitStream.ReadShortString();
            var converted_localPos = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datalocalPos = converted_localPos.ToUnityVector3();
    
            return new _006c748d7f8085f4691d554734b27fe0_b2e9ab4a4afa4a9b8f7d207ac3140fa7()
            {
                Entity = entity,
                Routing = target,
                playerID = dataplayerID,
                localPos = datalocalPos
            };   
        }
    }

}
