// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _006c748d7f8085f4691d554734b27fe0_8445149378463969736 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 SyncedProxyPosition;
            [FieldOffset(12)]
            public Quaternion SyncedProxyRotation;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8445149378463969736.SyncedProxyPositionMask;
            SyncedProxyPositionSimulationFrame = frame;
            FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8445149378463969736.SyncedProxyRotationMask;
            SyncedProxyRotationSimulationFrame = frame;
        }

        public static unsafe _006c748d7f8085f4691d554734b27fe0_8445149378463969736 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 28) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 28) " +
                    "for component with ID 21");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 21");
            }

            var orig = new _006c748d7f8085f4691d554734b27fe0_8445149378463969736();

            var comp = (Interop*)data;

            orig.SyncedProxyPosition = comp->SyncedProxyPosition;
            orig.SyncedProxyRotation = comp->SyncedProxyRotation;

            return orig;
        }


        public static uint SyncedProxyPositionMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame SyncedProxyPositionSimulationFrame;
        public Vector3 SyncedProxyPosition;
        public static uint SyncedProxyRotationMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame SyncedProxyRotationSimulationFrame;
        public Quaternion SyncedProxyRotation;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 21;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 2;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_006c748d7f8085f4691d554734b27fe0_8445149378463969736)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.SyncedProxyPositionSimulationFrame = other.SyncedProxyPositionSimulationFrame;
                this.SyncedProxyPosition = other.SyncedProxyPosition;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.SyncedProxyRotationSimulationFrame = other.SyncedProxyRotationSimulationFrame;
                this.SyncedProxyRotation = other.SyncedProxyRotation;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_006c748d7f8085f4691d554734b27fe0_8445149378463969736 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.SyncedProxyPosition.ToCoreVector3());



                bitStream.WriteVector3(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.SyncedProxyRotation.ToCoreQuaternion());



                bitStream.WriteQuaternion(fieldValue, 32);
            }

            mask >>= 1;

            return mask;
        }

        public static _006c748d7f8085f4691d554734b27fe0_8445149378463969736 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var val = new _006c748d7f8085f4691d554734b27fe0_8445149378463969736();
            if (bitStream.ReadMask())
            {

                val.SyncedProxyPosition = bitStream.ReadVector3(FloatMeta.NoCompression()).ToUnityVector3();
                val.FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8445149378463969736.SyncedProxyPositionMask;
            }
            if (bitStream.ReadMask())
            {

                val.SyncedProxyRotation = bitStream.ReadQuaternion(32).ToUnityQuaternion();
                val.FieldsMask |= _006c748d7f8085f4691d554734b27fe0_8445149378463969736.SyncedProxyRotationMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_006c748d7f8085f4691d554734b27fe0_8445149378463969736(" +
                $" SyncedProxyPosition: { this.SyncedProxyPosition }" +
                $" SyncedProxyRotation: { this.SyncedProxyRotation }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0') })";
        }
    }

}
