// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 startPos;
            [FieldOffset(12)]
            public Vector3 endPos;
        }

        public static unsafe _090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 24) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 24) " +
                    "for command with ID 14");
            }

            var orig = new _090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33();
            var comp = (Interop*)data;
            orig.startPos = comp->startPos;
            orig.endPos = comp->endPos;
            return orig;
        }

        public Vector3 startPos;
        public Vector3 endPos;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 14;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33(
        Entity entity,
        Vector3 startPos,
        Vector3 endPos
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.startPos = startPos; 
            this.endPos = endPos; 
        }
        
        public static void Serialize(_090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33 commandData, IOutProtocolBitStream bitStream)
        {
            var converted_startPos = commandData.startPos.ToCoreVector3();
            bitStream.WriteVector3(converted_startPos, FloatMeta.NoCompression());
            var converted_endPos = commandData.endPos.ToCoreVector3();
            bitStream.WriteVector3(converted_endPos, FloatMeta.NoCompression());
        }
        
        public static _090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var converted_startPos = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datastartPos = converted_startPos.ToUnityVector3();
            var converted_endPos = bitStream.ReadVector3(FloatMeta.NoCompression());
            var dataendPos = converted_endPos.ToUnityVector3();
    
            return new _090aa92f766769348b4882a9d6b148e2_efa262ebd6154f7b801cc9ea94e56f33()
            {
                Entity = entity,
                Routing = target,
                startPos = datastartPos,
                endPos = dataendPos
            };   
        }
    }

}
