// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 shootDirection;
            [FieldOffset(12)]
            public System.Single hitDistance;
        }

        public static unsafe _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 16) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for command with ID 9");
            }

            var orig = new _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb();
            var comp = (Interop*)data;
            orig.shootDirection = comp->shootDirection;
            orig.hitDistance = comp->hitDistance;
            return orig;
        }

        public Vector3 shootDirection;
        public System.Single hitDistance;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 9;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb(
        Entity entity,
        Vector3 shootDirection,
        System.Single hitDistance
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.shootDirection = shootDirection; 
            this.hitDistance = hitDistance; 
        }
        
        public static void Serialize(_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb commandData, IOutProtocolBitStream bitStream)
        {
            var converted_shootDirection = commandData.shootDirection.ToCoreVector3();
            bitStream.WriteVector3(converted_shootDirection, FloatMeta.NoCompression());
            bitStream.WriteFloat(commandData.hitDistance, FloatMeta.NoCompression());
        }
        
        public static _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var converted_shootDirection = bitStream.ReadVector3(FloatMeta.NoCompression());
            var datashootDirection = converted_shootDirection.ToUnityVector3();
            var datahitDistance = bitStream.ReadFloat(FloatMeta.NoCompression());
    
            return new _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb()
            {
                Entity = entity,
                Routing = target,
                shootDirection = datashootDirection,
                hitDistance = datahitDistance
            };   
        }
    }

}
