// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 SyncedProxyPosition;
            [FieldOffset(12)]
            public Quaternion SyncedProxyRotation;
            [FieldOffset(28)]
            public Vector3 Velocity;
            [FieldOffset(40)]
            public Vector3 AngularVelocity;
            [FieldOffset(52)]
            public System.Byte IsLanded;
            [FieldOffset(53)]
            public System.Byte enabled;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.SyncedProxyPositionMask;
            SyncedProxyPositionSimulationFrame = frame;
            FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.SyncedProxyRotationMask;
            SyncedProxyRotationSimulationFrame = frame;
            FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.VelocityMask;
            VelocitySimulationFrame = frame;
            FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.AngularVelocityMask;
            AngularVelocitySimulationFrame = frame;
            FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.IsLandedMask;
            IsLandedSimulationFrame = frame;
            FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.enabledMask;
            enabledSimulationFrame = frame;
        }

        public static unsafe _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 54) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 54) " +
                    "for component with ID 35");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 35");
            }

            var orig = new _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326();

            var comp = (Interop*)data;

            orig.SyncedProxyPosition = comp->SyncedProxyPosition;
            orig.SyncedProxyRotation = comp->SyncedProxyRotation;
            orig.Velocity = comp->Velocity;
            orig.AngularVelocity = comp->AngularVelocity;
            orig.IsLanded = comp->IsLanded != 0;
            orig.enabled = comp->enabled != 0;

            return orig;
        }


        public static uint SyncedProxyPositionMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame SyncedProxyPositionSimulationFrame;
        public Vector3 SyncedProxyPosition;
        public static uint SyncedProxyRotationMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame SyncedProxyRotationSimulationFrame;
        public Quaternion SyncedProxyRotation;
        public static uint VelocityMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame VelocitySimulationFrame;
        public Vector3 Velocity;
        public static uint AngularVelocityMask => 0b00000000000000000000000000001000;
        public AbsoluteSimulationFrame AngularVelocitySimulationFrame;
        public Vector3 AngularVelocity;
        public static uint IsLandedMask => 0b00000000000000000000000000010000;
        public AbsoluteSimulationFrame IsLandedSimulationFrame;
        public System.Boolean IsLanded;
        public static uint enabledMask => 0b00000000000000000000000000100000;
        public AbsoluteSimulationFrame enabledSimulationFrame;
        public System.Boolean enabled;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 35;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000111111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 6;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_afa2e919585b4d944ba7cd1178fefb07_3113483745782545326)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.SyncedProxyPositionSimulationFrame = other.SyncedProxyPositionSimulationFrame;
                this.SyncedProxyPosition = other.SyncedProxyPosition;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.SyncedProxyRotationSimulationFrame = other.SyncedProxyRotationSimulationFrame;
                this.SyncedProxyRotation = other.SyncedProxyRotation;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.VelocitySimulationFrame = other.VelocitySimulationFrame;
                this.Velocity = other.Velocity;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.AngularVelocitySimulationFrame = other.AngularVelocitySimulationFrame;
                this.AngularVelocity = other.AngularVelocity;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.IsLandedSimulationFrame = other.IsLandedSimulationFrame;
                this.IsLanded = other.IsLanded;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.enabledSimulationFrame = other.enabledSimulationFrame;
                this.enabled = other.enabled;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_afa2e919585b4d944ba7cd1178fefb07_3113483745782545326 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 6);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.SyncedProxyPosition.ToCoreVector3());



                bitStream.WriteVector3(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.SyncedProxyRotation.ToCoreQuaternion());



                bitStream.WriteQuaternion(fieldValue, 32);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.Velocity.ToCoreVector3());



                bitStream.WriteVector3(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = (data.AngularVelocity.ToCoreVector3());



                bitStream.WriteVector3(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.IsLanded;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.enabled;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;

            return mask;
        }

        public static _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(6);
            }

            var val = new _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326();
            if (bitStream.ReadMask())
            {

                val.SyncedProxyPosition = bitStream.ReadVector3(FloatMeta.NoCompression()).ToUnityVector3();
                val.FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.SyncedProxyPositionMask;
            }
            if (bitStream.ReadMask())
            {

                val.SyncedProxyRotation = bitStream.ReadQuaternion(32).ToUnityQuaternion();
                val.FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.SyncedProxyRotationMask;
            }
            if (bitStream.ReadMask())
            {

                val.Velocity = bitStream.ReadVector3(FloatMeta.NoCompression()).ToUnityVector3();
                val.FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.VelocityMask;
            }
            if (bitStream.ReadMask())
            {

                val.AngularVelocity = bitStream.ReadVector3(FloatMeta.NoCompression()).ToUnityVector3();
                val.FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.AngularVelocityMask;
            }
            if (bitStream.ReadMask())
            {

                val.IsLanded = bitStream.ReadBool();
                val.FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.IsLandedMask;
            }
            if (bitStream.ReadMask())
            {

                val.enabled = bitStream.ReadBool();
                val.FieldsMask |= _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.enabledMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_afa2e919585b4d944ba7cd1178fefb07_3113483745782545326(" +
                $" SyncedProxyPosition: { this.SyncedProxyPosition }" +
                $" SyncedProxyRotation: { this.SyncedProxyRotation }" +
                $" Velocity: { this.Velocity }" +
                $" AngularVelocity: { this.AngularVelocity }" +
                $" IsLanded: { this.IsLanded }" +
                $" enabled: { this.enabled }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(6, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(6, '0') })";
        }
    }

}
