// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Text;
    using Coherence;
    using Coherence.Brisk;
    using Coherence.ProtocolDef;
    using Coherence.Connection;
    using Coherence.Entities;
    using System.Collections.Generic;
    using Coherence.SimulationFrame;
    using Coherence.Core;

    public class DataInteropHandler : IDataInteropHandler
    {
        public unsafe ICoherenceComponentData GetComponent(UInt32 type, IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            switch(type)
            {
                case 0: return WorldPosition.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 1: return WorldOrientation.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 2: return LocalUserComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 3: return WorldPositionQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 4: return ArchetypeComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 5: return Persistence.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 6: return ConnectedEntity.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 7: return UniqueID.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 8: return Connection.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 9: return ConnectionScene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 10: return Global.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 11: return GlobalQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 12: return Tag.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 13: return TagQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 14: return PreserveChildren.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 15: return Scene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 16: return AssetId.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 17: return GenericScale.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 18: return _002e0f0727244a041abfd9d124ef5bce_3087197899905382071.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 19: return _002e0f0727244a041abfd9d124ef5bce_3087197899905382075.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 20: return _006c748d7f8085f4691d554734b27fe0_8362810714748207749.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 21: return _006c748d7f8085f4691d554734b27fe0_8445149378463969736.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 22: return _090aa92f766769348b4882a9d6b148e2_3543296725183664748.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 23: return _090aa92f766769348b4882a9d6b148e2_3543296725183664750.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 24: return _0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 25: return _0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 26: return _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 27: return _0f1baba4f59f64140a0ff46868bde78f_8597659800900311073.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 28: return _362fd1a7edeb85c48bb39119604133c5_7385481098666009946.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 29: return _362fd1a7edeb85c48bb39119604133c5_7385481098666009951.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 30: return _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 31: return _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 32: return _76ed9974a395ce54087bcb395f26407a_6959148627032638732.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 33: return _76ed9974a395ce54087bcb395f26407a_6959148627032638734.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 34: return _8b463149d5f8b1c4dab027c2c3ec2ad2_9074563940274071313.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 35: return _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 36: return _afa2e919585b4d944ba7cd1178fefb07_3474684778041906956.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 37: return _e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 38: return _e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 39: return _ff0eb699ebf32684891c45f672adc3ae_7001076288282754374.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 40: return _ff0eb699ebf32684891c45f672adc3ae_8801456816483979748.FromInterop(data, dataSize, simFrames, simFramesCount);
            }

            throw new ArgumentException($"Unkown component type {type}", nameof(type));
        }

        public unsafe void UpdateComponent(INativeCoreComponentUpdater updater, InteropEntity entity, ICoherenceComponentData component)
        {
            var componentType = component.GetComponentType();
            var frames = component.GetSimulationFrames();

            switch (componentType)
            {
                case 0:
                {
                    var orig = (WorldPosition)component;
                    var val = new WorldPosition.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 1:
                {
                    var orig = (WorldOrientation)component;
                    var val = new WorldOrientation.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 2:
                {
                    var orig = (LocalUserComponent)component;
                    var val = new LocalUserComponent.Interop();

                    val.localIndex = orig.localIndex;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 3:
                {
                    var orig = (WorldPositionQuery)component;
                    var val = new WorldPositionQuery.Interop();

                    val.position = orig.position;
                    val.radius = orig.radius;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 4:
                {
                    var orig = (ArchetypeComponent)component;
                    var val = new ArchetypeComponent.Interop();

                    val.index = orig.index;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 5:
                {
                    var orig = (Persistence)component;
                    var val = new Persistence.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 6:
                {
                    var orig = (ConnectedEntity)component;
                    var val = new ConnectedEntity.Interop();

                    val.value = orig.value;
                    val.pos = orig.pos;
                    val.rot = orig.rot;
                    val.scale = orig.scale;

                    updater.UpdateComponent(entity, componentType, val, 44, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 7:
                {
                    var orig = (UniqueID)component;
                    var val = new UniqueID.Interop();

                    var pinneduuid = orig.uuid != null ? Encoding.UTF8.GetBytes(orig.uuid) : null; fixed (void* pinnedPtruuid = pinneduuid) { val.uuid = new ByteArray { Data = pinnedPtruuid, Length =  pinneduuid?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 8:
                {
                    var orig = (Connection)component;
                    var val = new Connection.Interop();

                    val.id = orig.id;
                    val.type = orig.type;

                    updater.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 9:
                {
                    var orig = (ConnectionScene)component;
                    var val = new ConnectionScene.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 10:
                {
                    var orig = (Global)component;
                    var val = new Global.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 11:
                {
                    var orig = (GlobalQuery)component;
                    var val = new GlobalQuery.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 12:
                {
                    var orig = (Tag)component;
                    var val = new Tag.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 13:
                {
                    var orig = (TagQuery)component;
                    var val = new TagQuery.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 14:
                {
                    var orig = (PreserveChildren)component;
                    var val = new PreserveChildren.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 15:
                {
                    var orig = (Scene)component;
                    var val = new Scene.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 16:
                {
                    var orig = (AssetId)component;
                    var val = new AssetId.Interop();

                    val.value = orig.value;
                    val.isFromGroup = orig.isFromGroup ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 5, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 17:
                {
                    var orig = (GenericScale)component;
                    var val = new GenericScale.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 18:
                {
                    var orig = (_002e0f0727244a041abfd9d124ef5bce_3087197899905382071)component;
                    var val = new _002e0f0727244a041abfd9d124ef5bce_3087197899905382071.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;

                    updater.UpdateComponent(entity, componentType, val, 28, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 19:
                {
                    var orig = (_002e0f0727244a041abfd9d124ef5bce_3087197899905382075)component;
                    var val = new _002e0f0727244a041abfd9d124ef5bce_3087197899905382075.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 20:
                {
                    var orig = (_006c748d7f8085f4691d554734b27fe0_8362810714748207749)component;
                    var val = new _006c748d7f8085f4691d554734b27fe0_8362810714748207749.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;
                    val.NetworkIsControlled = orig.NetworkIsControlled ? (System.Byte)1 : (System.Byte)0;
                    val.ControllingPlayerGameObject = orig.ControllingPlayerGameObject;

                    updater.UpdateComponent(entity, componentType, val, 9, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 21:
                {
                    var orig = (_006c748d7f8085f4691d554734b27fe0_8445149378463969736)component;
                    var val = new _006c748d7f8085f4691d554734b27fe0_8445149378463969736.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;
                    val.AngularVelocity = orig.AngularVelocity;
                    val.Velocity = orig.Velocity;
                    val.IsLanded = orig.IsLanded ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 53, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 22:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_3543296725183664748)component;
                    var val = new _090aa92f766769348b4882a9d6b148e2_3543296725183664748.Interop();

                    val.AngularVelocity = orig.AngularVelocity;
                    val.Velocity = orig.Velocity;
                    val.IsLanded = orig.IsLanded ? (System.Byte)1 : (System.Byte)0;
                    val.enabled = orig.enabled ? (System.Byte)1 : (System.Byte)0;
                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;

                    updater.UpdateComponent(entity, componentType, val, 54, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 23:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_3543296725183664750)component;
                    var val = new _090aa92f766769348b4882a9d6b148e2_3543296725183664750.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 24:
                {
                    var orig = (_0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788)component;
                    var val = new _0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 25:
                {
                    var orig = (_0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101)component;
                    var val = new _0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;
                    val.Velocity = orig.Velocity;
                    val.AngularVelocity = orig.AngularVelocity;
                    val.IsLanded = orig.IsLanded ? (System.Byte)1 : (System.Byte)0;
                    val.enabled = orig.enabled ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 54, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 26:
                {
                    var orig = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)component;
                    var val = new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;
                    val.Velocity = orig.Velocity;
                    val.AngularVelocity = orig.AngularVelocity;
                    val.IsLanded = orig.IsLanded ? (System.Byte)1 : (System.Byte)0;
                    val.enabled = orig.enabled ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 54, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 27:
                {
                    var orig = (_0f1baba4f59f64140a0ff46868bde78f_8597659800900311073)component;
                    var val = new _0f1baba4f59f64140a0ff46868bde78f_8597659800900311073.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 28:
                {
                    var orig = (_362fd1a7edeb85c48bb39119604133c5_7385481098666009946)component;
                    var val = new _362fd1a7edeb85c48bb39119604133c5_7385481098666009946.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 29:
                {
                    var orig = (_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)component;
                    var val = new _362fd1a7edeb85c48bb39119604133c5_7385481098666009951.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;

                    updater.UpdateComponent(entity, componentType, val, 28, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 30:
                {
                    var orig = (_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761)component;
                    var val = new _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 31:
                {
                    var orig = (_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762)component;
                    var val = new _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762.Interop();

                    val.AngularVelocity = orig.AngularVelocity;
                    val.Velocity = orig.Velocity;
                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;

                    updater.UpdateComponent(entity, componentType, val, 52, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 32:
                {
                    var orig = (_76ed9974a395ce54087bcb395f26407a_6959148627032638732)component;
                    var val = new _76ed9974a395ce54087bcb395f26407a_6959148627032638732.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 33:
                {
                    var orig = (_76ed9974a395ce54087bcb395f26407a_6959148627032638734)component;
                    var val = new _76ed9974a395ce54087bcb395f26407a_6959148627032638734.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;

                    updater.UpdateComponent(entity, componentType, val, 28, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 34:
                {
                    var orig = (_8b463149d5f8b1c4dab027c2c3ec2ad2_9074563940274071313)component;
                    var val = new _8b463149d5f8b1c4dab027c2c3ec2ad2_9074563940274071313.Interop();

                    val.totalEatenCount = orig.totalEatenCount;
                    val.hasYellowBeenEaten = orig.hasYellowBeenEaten ? (System.Byte)1 : (System.Byte)0;
                    val.hasGreenBeenEaten = orig.hasGreenBeenEaten ? (System.Byte)1 : (System.Byte)0;
                    val.hasWon = orig.hasWon ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 7, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 35:
                {
                    var orig = (_afa2e919585b4d944ba7cd1178fefb07_3113483745782545326)component;
                    var val = new _afa2e919585b4d944ba7cd1178fefb07_3113483745782545326.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;
                    val.Velocity = orig.Velocity;
                    val.AngularVelocity = orig.AngularVelocity;
                    val.IsLanded = orig.IsLanded ? (System.Byte)1 : (System.Byte)0;
                    val.enabled = orig.enabled ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 54, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 36:
                {
                    var orig = (_afa2e919585b4d944ba7cd1178fefb07_3474684778041906956)component;
                    var val = new _afa2e919585b4d944ba7cd1178fefb07_3474684778041906956.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 37:
                {
                    var orig = (_e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893)component;
                    var val = new _e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 38:
                {
                    var orig = (_e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462)component;
                    var val = new _e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;

                    updater.UpdateComponent(entity, componentType, val, 28, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 39:
                {
                    var orig = (_ff0eb699ebf32684891c45f672adc3ae_7001076288282754374)component;
                    var val = new _ff0eb699ebf32684891c45f672adc3ae_7001076288282754374.Interop();

                    val.SyncedProxyPosition = orig.SyncedProxyPosition;
                    val.SyncedProxyRotation = orig.SyncedProxyRotation;
                    val.Velocity = orig.Velocity;
                    val.AngularVelocity = orig.AngularVelocity;
                    val.IsLanded = orig.IsLanded ? (System.Byte)1 : (System.Byte)0;
                    val.enabled = orig.enabled ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 54, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 40:
                {
                    var orig = (_ff0eb699ebf32684891c45f672adc3ae_8801456816483979748)component;
                    var val = new _ff0eb699ebf32684891c45f672adc3ae_8801456816483979748.Interop();

                    val.networkedCurrentFieldTransform = orig.networkedCurrentFieldTransform;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
            }

            throw new NotImplementedException($"Failed to update a component with type {componentType}.");
        }

        public unsafe IEntityCommand GetCommand(UInt32 type, IntPtr data, Int32 dataSize)
        {
            switch (type)
            {
                  case 0: return AuthorityRequest.FromInterop(data, dataSize);
                  case 1: return AuthorityTransfer.FromInterop(data, dataSize);
                  case 2: return QuerySynced.FromInterop(data, dataSize);
                  case 3: return AdoptOrphan.FromInterop(data, dataSize);
                  case 4: return PersistenceReady.FromInterop(data, dataSize);
                  case 5: return SceneIndexChanged.FromInterop(data, dataSize);
                  case 6: return _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64.FromInterop(data, dataSize);
                  case 7: return _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0.FromInterop(data, dataSize);
                  case 8: return _006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398.FromInterop(data, dataSize);
                  case 9: return _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb.FromInterop(data, dataSize);
                  case 10: return _090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2.FromInterop(data, dataSize);
                  case 11: return _090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af.FromInterop(data, dataSize);
                  case 12: return _090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7.FromInterop(data, dataSize);
                  case 13: return _090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f.FromInterop(data, dataSize);
                  case 14: return _090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12.FromInterop(data, dataSize);
                  case 15: return _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847.FromInterop(data, dataSize);
                  case 16: return _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708.FromInterop(data, dataSize);
                  case 17: return _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39.FromInterop(data, dataSize);
                  case 18: return _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1.FromInterop(data, dataSize);
                  case 19: return _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092.FromInterop(data, dataSize);
                  case 20: return _4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73.FromInterop(data, dataSize);
                  case 21: return _4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b.FromInterop(data, dataSize);
                  case 22: return _4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44.FromInterop(data, dataSize);
                  case 23: return _8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569.FromInterop(data, dataSize);
                  case 24: return _8b463149d5f8b1c4dab027c2c3ec2ad2_d308afb07a204decae0628f55b2b1ff5.FromInterop(data, dataSize);
                  case 25: return _8b463149d5f8b1c4dab027c2c3ec2ad2_e8356f9054e940f1b66e83a6c0b6bc39.FromInterop(data, dataSize);
                  case 26: return _afa2e919585b4d944ba7cd1178fefb07_658f49f164494f099ca2780d21d0a847.FromInterop(data, dataSize);
                  case 27: return _ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847.FromInterop(data, dataSize);
            }

            throw new ArgumentException($"Unkown command type {type}", nameof(type));
        }

        public unsafe IEntityInput GetInput(UInt32 type, IntPtr data, Int32 dataSize)
        {
            throw new ArgumentException($"Unknown input type {type}", nameof(type));
        }

        public unsafe bool SendCommand(INativeCoreCommandSender sender, InteropEntity entity, MessageTarget target, IEntityCommand command)
        {
            var type = command.GetComponentType();
            switch (type)
            {
                case 0:
                {
                    var orig = (AuthorityRequest)command;
                    var val = new AuthorityRequest.Interop();

                    val.requester = orig.requester;
                    val.authorityType = orig.authorityType;

                    return sender.SendCommand(entity, target, type, val, 8);

                }
                case 1:
                {
                    var orig = (AuthorityTransfer)command;
                    var val = new AuthorityTransfer.Interop();

                    val.newAuthority = orig.newAuthority;
                    val.accepted = orig.accepted ? (System.Byte)1 : (System.Byte)0;
                    val.authorityType = orig.authorityType;

                    return sender.SendCommand(entity, target, type, val, 9);

                }
                case 2:
                {
                    var orig = (QuerySynced)command;
                    var val = new QuerySynced.Interop();

                    val.liveQuerySynced = orig.liveQuerySynced ? (System.Byte)1 : (System.Byte)0;
                    val.globalQuerySynced = orig.globalQuerySynced ? (System.Byte)1 : (System.Byte)0;

                    return sender.SendCommand(entity, target, type, val, 2);

                }
                case 3:
                {
                    var orig = (AdoptOrphan)command;
                    var val = new AdoptOrphan.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 4:
                {
                    var orig = (PersistenceReady)command;
                    var val = new PersistenceReady.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 5:
                {
                    var orig = (SceneIndexChanged)command;
                    var val = new SceneIndexChanged.Interop();

                    val.sceneIndex = orig.sceneIndex;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 6:
                {
                    var orig = (_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64)command;
                    var val = new _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64.Interop();

                    val.playerGameObject = orig.playerGameObject;
                    val.localPos = orig.localPos;

                    return sender.SendCommand(entity, target, type, val, 16);

                }
                case 7:
                {
                    var orig = (_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0)command;
                    var val = new _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 8:
                {
                    var orig = (_006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398)command;
                    var val = new _006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 9:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb)command;
                    var val = new _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb.Interop();

                    val.shootDirection = orig.shootDirection;
                    val.hitDistance = orig.hitDistance;

                    return sender.SendCommand(entity, target, type, val, 16);

                }
                case 10:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2)command;
                    var val = new _090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 11:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af)command;
                    var val = new _090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 12:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7)command;
                    var val = new _090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7.Interop();

                    val.shootDirection = orig.shootDirection;

                    return sender.SendCommand(entity, target, type, val, 12);

                }
                case 13:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f)command;
                    var val = new _090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f.Interop();

                    val.amount = orig.amount;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 14:
                {
                    var orig = (_090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12)command;
                    var val = new _090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 15:
                {
                    var orig = (_0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847)command;
                    var val = new _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 16:
                {
                    var orig = (_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708)command;
                    var val = new _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 17:
                {
                    var orig = (_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39)command;
                    var val = new _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 18:
                {
                    var orig = (_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1)command;
                    var val = new _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 19:
                {
                    var orig = (_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092)command;
                    var val = new _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 20:
                {
                    var orig = (_4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73)command;
                    var val = new _4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 21:
                {
                    var orig = (_4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b)command;
                    var val = new _4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 22:
                {
                    var orig = (_4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44)command;
                    var val = new _4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 23:
                {
                    var orig = (_8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569)command;
                    var val = new _8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569.Interop();

                    val.spawnTransform = orig.spawnTransform;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 24:
                {
                    var orig = (_8b463149d5f8b1c4dab027c2c3ec2ad2_d308afb07a204decae0628f55b2b1ff5)command;
                    var val = new _8b463149d5f8b1c4dab027c2c3ec2ad2_d308afb07a204decae0628f55b2b1ff5.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 25:
                {
                    var orig = (_8b463149d5f8b1c4dab027c2c3ec2ad2_e8356f9054e940f1b66e83a6c0b6bc39)command;
                    var val = new _8b463149d5f8b1c4dab027c2c3ec2ad2_e8356f9054e940f1b66e83a6c0b6bc39.Interop();

                    val.typeInt = orig.typeInt;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 26:
                {
                    var orig = (_afa2e919585b4d944ba7cd1178fefb07_658f49f164494f099ca2780d21d0a847)command;
                    var val = new _afa2e919585b4d944ba7cd1178fefb07_658f49f164494f099ca2780d21d0a847.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 27:
                {
                    var orig = (_ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847)command;
                    var val = new _ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847.Interop();

                    val.playerGameObject = orig.playerGameObject;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
            }

            throw new NotImplementedException($"Failed to send a command with type {type}.");
        }

        public unsafe void SendInput(INativeCoreInputSender sender, InteropEntity entity, long frame, IEntityInput input)
        {
            var type = input.GetComponentType();

            throw new NotImplementedException($"Failed to send an input with type {type}.");
        }
    }

}
