// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_a1b01801ddfb4f919e050a206ddef524 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_b72198b2c9d14e9191eb8cd98835a77d : ReferenceBinding
    {   
        private global::Gravitas.GravitasSubject CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasSubject)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_8597659800900311073);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_8597659800900311073";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override Entity Value
        {
            get { return coherenceSync.CoherenceBridge.UnityObjectToEntityId(CastedUnityComponent.networkedCurrentFieldTransform); }
            set { CastedUnityComponent.networkedCurrentFieldTransform = coherenceSync.CoherenceBridge.EntityIdToTransform(value); }
        }

        protected override (Entity value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_8597659800900311073)coherenceComponent).networkedCurrentFieldTransform;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_8597659800900311073)coherenceComponent).networkedCurrentFieldTransformSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_8597659800900311073)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.networkedCurrentFieldTransform = Value;
            }
            else
            {
                update.networkedCurrentFieldTransform = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.networkedCurrentFieldTransformSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_8597659800900311073();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_57c7f9195bcb40668ca6c81a2cdc5341 : Vector3Binding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.SyncedProxyPosition); }
            set { CastedUnityComponent.SyncedProxyPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).SyncedProxyPosition;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).SyncedProxyPositionSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyPosition = Value;
            }
            else
            {
                update.SyncedProxyPosition = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyPositionSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_aea6c1a42ee849b5801a9c997b3d9666 : QuaternionBinding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.SyncedProxyRotation); }
            set { CastedUnityComponent.SyncedProxyRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).SyncedProxyRotation;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).SyncedProxyRotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyRotation = Value;
            }
            else
            {
                update.SyncedProxyRotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyRotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_d64955ab3ec84a0a981591bb9b10d620 : Vector3Binding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.Velocity); }
            set { CastedUnityComponent.Velocity = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).Velocity;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).VelocitySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Velocity = Value;
            }
            else
            {
                update.Velocity = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.VelocitySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_61e4698d21524001b97ad4e917cd43f9 : Vector3Binding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.AngularVelocity); }
            set { CastedUnityComponent.AngularVelocity = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).AngularVelocity;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).AngularVelocitySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.AngularVelocity = Value;
            }
            else
            {
                update.AngularVelocity = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.AngularVelocitySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_40870536dee24460a6ae7d856163c6ca : BoolBinding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.IsLanded); }
            set { CastedUnityComponent.IsLanded = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).IsLanded;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).IsLandedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsLanded = Value;
            }
            else
            {
                update.IsLanded = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsLandedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f1baba4f59f64140a0ff46868bde78f_77b03868c61f4265afed3467a9bb3a34 : BoolBinding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203);
        public override string CoherenceComponentName => "_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203";
        public override uint FieldMask => 0b00000000000000000000000000100000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).enabled;

            var simFrame = ((_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f1baba4f59f64140a0ff46868bde78f_7808355085924611203)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f1baba4f59f64140a0ff46868bde78f_7808355085924611203();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0f1baba4f59f64140a0ff46868bde78f : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0f1baba4f59f64140a0ff46868bde78f>();
        
        private global::Gravitas.FoodBall _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["a1b01801ddfb4f919e050a206ddef524"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_a1b01801ddfb4f919e050a206ddef524(),
			["b72198b2c9d14e9191eb8cd98835a77d"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_b72198b2c9d14e9191eb8cd98835a77d(),
			["57c7f9195bcb40668ca6c81a2cdc5341"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_57c7f9195bcb40668ca6c81a2cdc5341(),
			["aea6c1a42ee849b5801a9c997b3d9666"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_aea6c1a42ee849b5801a9c997b3d9666(),
			["d64955ab3ec84a0a981591bb9b10d620"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_d64955ab3ec84a0a981591bb9b10d620(),
			["61e4698d21524001b97ad4e917cd43f9"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_61e4698d21524001b97ad4e917cd43f9(),
			["40870536dee24460a6ae7d856163c6ca"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_40870536dee24460a6ae7d856163c6ca(),
			["77b03868c61f4265afed3467a9bb3a34"] = new Binding_0f1baba4f59f64140a0ff46868bde78f_77b03868c61f4265afed3467a9bb3a34(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0f1baba4f59f64140a0ff46868bde78f()
        {
            bakedCommandBindings.Add("658f49f164494f099ca2780d21d0a847", BakeCommandBinding__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847_CommandTarget = (global::Gravitas.FoodBall)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.FoodBall.NetworkEatFoodBall", "(UnityEngine.GameObject)", SendCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847, ReceiveLocalCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847, MessageTarget.All, _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847_CommandTarget, false);
        }
        
        private void SendCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            
            ReceiveCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847(command);
        }

        private void ReceiveCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847(_0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847 command)
        {
            var target = _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847_CommandTarget;
            
            target.NetworkEatFoodBall(bridge.EntityIdToGameObject(command.playerGameObject));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847 castedCommand:
                    ReceiveCommand__0f1baba4f59f64140a0ff46868bde78f_658f49f164494f099ca2780d21d0a847(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0f1baba4f59f64140a0ff46868bde78f Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0f1baba4f59f64140a0ff46868bde78f>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
