// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_76ed9974a395ce54087bcb395f26407a_f584ff4cf1e247999feac45fb39f54cf : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_76ed9974a395ce54087bcb395f26407a_44480524014643f0ae9e00b9735c5e8b : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_76ed9974a395ce54087bcb395f26407a_5a48831e0adc413b8a3cc83364f1ea7f : Vector3Binding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_76ed9974a395ce54087bcb395f26407a_6959148627032638734);
        public override string CoherenceComponentName => "_76ed9974a395ce54087bcb395f26407a_6959148627032638734";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.SyncedProxyPosition); }
            set { CastedUnityComponent.SyncedProxyPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_76ed9974a395ce54087bcb395f26407a_6959148627032638734)coherenceComponent).SyncedProxyPosition;

            var simFrame = ((_76ed9974a395ce54087bcb395f26407a_6959148627032638734)coherenceComponent).SyncedProxyPositionSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_76ed9974a395ce54087bcb395f26407a_6959148627032638734)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyPosition = Value;
            }
            else
            {
                update.SyncedProxyPosition = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyPositionSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _76ed9974a395ce54087bcb395f26407a_6959148627032638734();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_76ed9974a395ce54087bcb395f26407a_bf2a363e648940c2bffadbbfd38df7e9 : QuaternionBinding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_76ed9974a395ce54087bcb395f26407a_6959148627032638734);
        public override string CoherenceComponentName => "_76ed9974a395ce54087bcb395f26407a_6959148627032638734";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.SyncedProxyRotation); }
            set { CastedUnityComponent.SyncedProxyRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_76ed9974a395ce54087bcb395f26407a_6959148627032638734)coherenceComponent).SyncedProxyRotation;

            var simFrame = ((_76ed9974a395ce54087bcb395f26407a_6959148627032638734)coherenceComponent).SyncedProxyRotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_76ed9974a395ce54087bcb395f26407a_6959148627032638734)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyRotation = Value;
            }
            else
            {
                update.SyncedProxyRotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyRotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _76ed9974a395ce54087bcb395f26407a_6959148627032638734();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_76ed9974a395ce54087bcb395f26407a_3d2c63862ef84e93838e6eeaddef4367 : StringBinding
    {   
        private global::Gravitas.GravitasSubject CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasSubject)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_76ed9974a395ce54087bcb395f26407a_6959148627032638732);
        public override string CoherenceComponentName => "_76ed9974a395ce54087bcb395f26407a_6959148627032638732";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.networkedCurrentFieldId); }
            set { CastedUnityComponent.networkedCurrentFieldId = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_76ed9974a395ce54087bcb395f26407a_6959148627032638732)coherenceComponent).networkedCurrentFieldId;

            var simFrame = ((_76ed9974a395ce54087bcb395f26407a_6959148627032638732)coherenceComponent).networkedCurrentFieldIdSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_76ed9974a395ce54087bcb395f26407a_6959148627032638732)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.networkedCurrentFieldId = Value;
            }
            else
            {
                update.networkedCurrentFieldId = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.networkedCurrentFieldIdSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _76ed9974a395ce54087bcb395f26407a_6959148627032638732();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_76ed9974a395ce54087bcb395f26407a : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_76ed9974a395ce54087bcb395f26407a>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["f584ff4cf1e247999feac45fb39f54cf"] = new Binding_76ed9974a395ce54087bcb395f26407a_f584ff4cf1e247999feac45fb39f54cf(),
			["44480524014643f0ae9e00b9735c5e8b"] = new Binding_76ed9974a395ce54087bcb395f26407a_44480524014643f0ae9e00b9735c5e8b(),
			["5a48831e0adc413b8a3cc83364f1ea7f"] = new Binding_76ed9974a395ce54087bcb395f26407a_5a48831e0adc413b8a3cc83364f1ea7f(),
			["bf2a363e648940c2bffadbbfd38df7e9"] = new Binding_76ed9974a395ce54087bcb395f26407a_bf2a363e648940c2bffadbbfd38df7e9(),
			["3d2c63862ef84e93838e6eeaddef4367"] = new Binding_76ed9974a395ce54087bcb395f26407a_3d2c63862ef84e93838e6eeaddef4367(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_76ed9974a395ce54087bcb395f26407a()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_76ed9974a395ce54087bcb395f26407a Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_76ed9974a395ce54087bcb395f26407a>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
