// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_006c748d7f8085f4691d554734b27fe0_9d1c197cab58420b80a4819063d92e3c : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_006c748d7f8085f4691d554734b27fe0_5367008f77ad4dcd88b9f3a92198da67 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_006c748d7f8085f4691d554734b27fe0_e95ef7f569ac403cabc7b48218d177db : Vector3Binding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_006c748d7f8085f4691d554734b27fe0_8445149378463969736);
        public override string CoherenceComponentName => "_006c748d7f8085f4691d554734b27fe0_8445149378463969736";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.SyncedProxyPosition); }
            set { CastedUnityComponent.SyncedProxyPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_006c748d7f8085f4691d554734b27fe0_8445149378463969736)coherenceComponent).SyncedProxyPosition;

            var simFrame = ((_006c748d7f8085f4691d554734b27fe0_8445149378463969736)coherenceComponent).SyncedProxyPositionSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_006c748d7f8085f4691d554734b27fe0_8445149378463969736)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyPosition = Value;
            }
            else
            {
                update.SyncedProxyPosition = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyPositionSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _006c748d7f8085f4691d554734b27fe0_8445149378463969736();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_006c748d7f8085f4691d554734b27fe0_70cfe5a3997f4a8b8db188c418011625 : QuaternionBinding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_006c748d7f8085f4691d554734b27fe0_8445149378463969736);
        public override string CoherenceComponentName => "_006c748d7f8085f4691d554734b27fe0_8445149378463969736";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.SyncedProxyRotation); }
            set { CastedUnityComponent.SyncedProxyRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_006c748d7f8085f4691d554734b27fe0_8445149378463969736)coherenceComponent).SyncedProxyRotation;

            var simFrame = ((_006c748d7f8085f4691d554734b27fe0_8445149378463969736)coherenceComponent).SyncedProxyRotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_006c748d7f8085f4691d554734b27fe0_8445149378463969736)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyRotation = Value;
            }
            else
            {
                update.SyncedProxyRotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyRotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _006c748d7f8085f4691d554734b27fe0_8445149378463969736();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_006c748d7f8085f4691d554734b27fe0_ed9ea47fd7ff4853a9b83dfa99ea8958 : StringBinding
    {   
        private global::Gravitas.Demo.GravitasSpaceshipSubject CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.Demo.GravitasSpaceshipSubject)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_006c748d7f8085f4691d554734b27fe0_8362810714748207749);
        public override string CoherenceComponentName => "_006c748d7f8085f4691d554734b27fe0_8362810714748207749";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.networkedCurrentFieldId); }
            set { CastedUnityComponent.networkedCurrentFieldId = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_006c748d7f8085f4691d554734b27fe0_8362810714748207749)coherenceComponent).networkedCurrentFieldId;

            var simFrame = ((_006c748d7f8085f4691d554734b27fe0_8362810714748207749)coherenceComponent).networkedCurrentFieldIdSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_006c748d7f8085f4691d554734b27fe0_8362810714748207749)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.networkedCurrentFieldId = Value;
            }
            else
            {
                update.networkedCurrentFieldId = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.networkedCurrentFieldIdSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _006c748d7f8085f4691d554734b27fe0_8362810714748207749();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_006c748d7f8085f4691d554734b27fe0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_006c748d7f8085f4691d554734b27fe0>();
        
        private global::Gravitas.Demo.GravitasSpaceshipSubject _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0_CommandTarget;
        private global::Gravitas.Demo.GravitasSpaceshipSubject _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["9d1c197cab58420b80a4819063d92e3c"] = new Binding_006c748d7f8085f4691d554734b27fe0_9d1c197cab58420b80a4819063d92e3c(),
			["5367008f77ad4dcd88b9f3a92198da67"] = new Binding_006c748d7f8085f4691d554734b27fe0_5367008f77ad4dcd88b9f3a92198da67(),
			["e95ef7f569ac403cabc7b48218d177db"] = new Binding_006c748d7f8085f4691d554734b27fe0_e95ef7f569ac403cabc7b48218d177db(),
			["70cfe5a3997f4a8b8db188c418011625"] = new Binding_006c748d7f8085f4691d554734b27fe0_70cfe5a3997f4a8b8db188c418011625(),
			["ed9ea47fd7ff4853a9b83dfa99ea8958"] = new Binding_006c748d7f8085f4691d554734b27fe0_ed9ea47fd7ff4853a9b83dfa99ea8958(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_006c748d7f8085f4691d554734b27fe0()
        {
            bakedCommandBindings.Add("c71970d4b58a42738f53e2cd22aee1c0", BakeCommandBinding__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0);
            bakedCommandBindings.Add("1ed269a9290d485ab7ad3dc6dd3b4b64", BakeCommandBinding__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0_CommandTarget = (global::Gravitas.Demo.GravitasSpaceshipSubject)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.Demo.GravitasSpaceshipSubject.NetworkExitSpaceship", "()", SendCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0, ReceiveLocalCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0, MessageTarget.All, _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0_CommandTarget, false);
        }
        
        private void SendCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0();
            
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0();
            
            
            ReceiveCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0(command);
        }

        private void ReceiveCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0(_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0 command)
        {
            var target = _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0_CommandTarget;
            
            target.NetworkExitSpaceship();
        }
        private void BakeCommandBinding__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64_CommandTarget = (global::Gravitas.Demo.GravitasSpaceshipSubject)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.Demo.GravitasSpaceshipSubject.NetworkSetPlayerController", "(UnityEngine.GameObjectUnityEngine.Vector3)", SendCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64, ReceiveLocalCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64, MessageTarget.All, _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64_CommandTarget, false);
        }
        
        private void SendCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            command.localPos = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            command.localPos = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(command);
        }

        private void ReceiveCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 command)
        {
            var target = _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64_CommandTarget;
            
            target.NetworkSetPlayerController(bridge.EntityIdToGameObject(command.playerGameObject),(UnityEngine.Vector3)(command.localPos));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0 castedCommand:
                    ReceiveCommand__006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0(castedCommand);
                    break;
                case _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 castedCommand:
                    ReceiveCommand__006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_006c748d7f8085f4691d554734b27fe0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_006c748d7f8085f4691d554734b27fe0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
