// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_4452a7764deb5654580ba23565e59e56_c6d5cd738c4c44709191ecebadab7c96 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_4452a7764deb5654580ba23565e59e56 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_4452a7764deb5654580ba23565e59e56>();
        
        private global::Gravitas.FoodBallTree _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["c6d5cd738c4c44709191ecebadab7c96"] = new Binding_4452a7764deb5654580ba23565e59e56_c6d5cd738c4c44709191ecebadab7c96(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_4452a7764deb5654580ba23565e59e56()
        {
            bakedCommandBindings.Add("05c87585ce1a4602823f38746d382092", BakeCommandBinding__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092_CommandTarget = (global::Gravitas.FoodBallTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.FoodBallTree.NetworkHarvestFoodBalls", "(UnityEngine.GameObject)", SendCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092, ReceiveLocalCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092, MessageTarget.All, _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092_CommandTarget, false);
        }
        
        private void SendCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            
            ReceiveCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092(command);
        }

        private void ReceiveCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092(_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092 command)
        {
            var target = _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092_CommandTarget;
            
            target.NetworkHarvestFoodBalls(bridge.EntityIdToGameObject(command.playerGameObject));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092 castedCommand:
                    ReceiveCommand__4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_4452a7764deb5654580ba23565e59e56 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_4452a7764deb5654580ba23565e59e56>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
