// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_362fd1a7edeb85c48bb39119604133c5_2219642d985c4a6bb4320c7d3f226c07 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_362fd1a7edeb85c48bb39119604133c5_83ee9c3c43c745a5acda36de9d65eded : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_362fd1a7edeb85c48bb39119604133c5_e5bdd009dadb4e3eb8fdd44255110da4 : ReferenceBinding
    {   
        private global::Gravitas.GravitasSubject CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasSubject)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_362fd1a7edeb85c48bb39119604133c5_7385481098666009946);
        public override string CoherenceComponentName => "_362fd1a7edeb85c48bb39119604133c5_7385481098666009946";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override Entity Value
        {
            get { return coherenceSync.CoherenceBridge.UnityObjectToEntityId(CastedUnityComponent.networkedCurrentFieldTransform); }
            set { CastedUnityComponent.networkedCurrentFieldTransform = coherenceSync.CoherenceBridge.EntityIdToTransform(value); }
        }

        protected override (Entity value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_362fd1a7edeb85c48bb39119604133c5_7385481098666009946)coherenceComponent).networkedCurrentFieldTransform;

            var simFrame = ((_362fd1a7edeb85c48bb39119604133c5_7385481098666009946)coherenceComponent).networkedCurrentFieldTransformSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_362fd1a7edeb85c48bb39119604133c5_7385481098666009946)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.networkedCurrentFieldTransform = Value;
            }
            else
            {
                update.networkedCurrentFieldTransform = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.networkedCurrentFieldTransformSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _362fd1a7edeb85c48bb39119604133c5_7385481098666009946();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_362fd1a7edeb85c48bb39119604133c5_3d78c4ced67b48028429be40f816d188 : Vector3Binding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_362fd1a7edeb85c48bb39119604133c5_7385481098666009951);
        public override string CoherenceComponentName => "_362fd1a7edeb85c48bb39119604133c5_7385481098666009951";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.SyncedProxyPosition); }
            set { CastedUnityComponent.SyncedProxyPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)coherenceComponent).SyncedProxyPosition;

            var simFrame = ((_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)coherenceComponent).SyncedProxyPositionSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyPosition = Value;
            }
            else
            {
                update.SyncedProxyPosition = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyPositionSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _362fd1a7edeb85c48bb39119604133c5_7385481098666009951();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_362fd1a7edeb85c48bb39119604133c5_d3790ce3e08141388e52dcfd38e1c099 : QuaternionBinding
    {   
        private global::Gravitas.GravitasBody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Gravitas.GravitasBody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_362fd1a7edeb85c48bb39119604133c5_7385481098666009951);
        public override string CoherenceComponentName => "_362fd1a7edeb85c48bb39119604133c5_7385481098666009951";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.SyncedProxyRotation); }
            set { CastedUnityComponent.SyncedProxyRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)coherenceComponent).SyncedProxyRotation;

            var simFrame = ((_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)coherenceComponent).SyncedProxyRotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.SyncedProxyRotation = Value;
            }
            else
            {
                update.SyncedProxyRotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SyncedProxyRotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _362fd1a7edeb85c48bb39119604133c5_7385481098666009951();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_362fd1a7edeb85c48bb39119604133c5 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_362fd1a7edeb85c48bb39119604133c5>();
        
        private global::Gravitas.FoodBallTree _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39_CommandTarget;
        private global::Gravitas.FoodBallTree _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708_CommandTarget;
        private global::Gravitas.FoodBallTree _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["2219642d985c4a6bb4320c7d3f226c07"] = new Binding_362fd1a7edeb85c48bb39119604133c5_2219642d985c4a6bb4320c7d3f226c07(),
			["83ee9c3c43c745a5acda36de9d65eded"] = new Binding_362fd1a7edeb85c48bb39119604133c5_83ee9c3c43c745a5acda36de9d65eded(),
			["e5bdd009dadb4e3eb8fdd44255110da4"] = new Binding_362fd1a7edeb85c48bb39119604133c5_e5bdd009dadb4e3eb8fdd44255110da4(),
			["3d78c4ced67b48028429be40f816d188"] = new Binding_362fd1a7edeb85c48bb39119604133c5_3d78c4ced67b48028429be40f816d188(),
			["d3790ce3e08141388e52dcfd38e1c099"] = new Binding_362fd1a7edeb85c48bb39119604133c5_d3790ce3e08141388e52dcfd38e1c099(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_362fd1a7edeb85c48bb39119604133c5()
        {
            bakedCommandBindings.Add("5f7ece0daa0c4c91a021a802c3f47f39", BakeCommandBinding__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39);
            bakedCommandBindings.Add("33c865cdc8d14dcf82e779420dab9708", BakeCommandBinding__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708);
            bakedCommandBindings.Add("a385adf88dc64bb493660ec8bcbed6d1", BakeCommandBinding__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39_CommandTarget = (global::Gravitas.FoodBallTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.FoodBallTree.NetworkHarvestFoodBalls", "(UnityEngine.GameObject)", SendCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39, ReceiveLocalCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39, MessageTarget.All, _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39_CommandTarget, false);
        }
        
        private void SendCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            
            ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39(command);
        }

        private void ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39(_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39 command)
        {
            var target = _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39_CommandTarget;
            
            target.NetworkHarvestFoodBalls(bridge.EntityIdToGameObject(command.playerGameObject));
        }
        private void BakeCommandBinding__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708_CommandTarget = (global::Gravitas.FoodBallTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.FoodBallTree.NetworkHarvestFoodBalls", "(UnityEngine.GameObject)", SendCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708, ReceiveLocalCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708, MessageTarget.All, _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708_CommandTarget, false);
        }
        
        private void SendCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            
            ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708(command);
        }

        private void ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708(_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708 command)
        {
            var target = _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708_CommandTarget;
            
            target.NetworkHarvestFoodBalls(bridge.EntityIdToGameObject(command.playerGameObject));
        }
        private void BakeCommandBinding__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1_CommandTarget = (global::Gravitas.FoodBallTree)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Gravitas.FoodBallTree.NetworkHarvestFoodBalls", "(UnityEngine.GameObject)", SendCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1, ReceiveLocalCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1, MessageTarget.All, _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1_CommandTarget, false);
        }
        
        private void SendCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1();
            
            int i = 0;
            command.playerGameObject = (Entity)bridge.UnityObjectToEntityId(args[i++] as UnityEngine.GameObject);
            
            ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1(command);
        }

        private void ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1(_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1 command)
        {
            var target = _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1_CommandTarget;
            
            target.NetworkHarvestFoodBalls(bridge.EntityIdToGameObject(command.playerGameObject));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39 castedCommand:
                    ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39(castedCommand);
                    break;
                case _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708 castedCommand:
                    ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708(castedCommand);
                    break;
                case _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1 castedCommand:
                    ReceiveCommand__362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_362fd1a7edeb85c48bb39119604133c5 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_362fd1a7edeb85c48bb39119604133c5>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
