// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Connection;
    using Coherence.Entities;
    using Coherence.Serializer;
    using Coherence.Log;
    using Coherence.SimulationFrame;


    [UnityEngine.Scripting.Preserve]

    public class Definition : IDefinition
    {
        public const string schemaId = "41b9a5fe80fe19970b18358261b077c347a92d09";
        public const uint InternalWorldPosition = 0;
        public const uint InternalWorldOrientation = 1;
        public const uint InternalLocalUserComponent = 2;
        public const uint InternalWorldPositionQuery = 3;
        public const uint InternalArchetypeComponent = 4;
        public const uint InternalPersistence = 5;
        public const uint InternalConnectedEntity = 6;
        public const uint InternalUniqueID = 7;
        public const uint InternalConnection = 8;
        public const uint InternalConnectionScene = 9;
        public const uint InternalGlobal = 10;
        public const uint InternalGlobalQuery = 11;
        public const uint InternalTag = 12;
        public const uint InternalTagQuery = 13;
        public const uint InternalPreserveChildren = 14;
        public const uint InternalScene = 15;
        public const uint InternalAssetId = 16;
        public const uint InternalGenericScale = 17;
        public const uint Internal_002e0f0727244a041abfd9d124ef5bce_3087197899905382071 = 18;
        public const uint Internal_002e0f0727244a041abfd9d124ef5bce_3087197899905382075 = 19;
        public const uint Internal_006c748d7f8085f4691d554734b27fe0_8362810714748207749 = 20;
        public const uint Internal_006c748d7f8085f4691d554734b27fe0_8445149378463969736 = 21;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_3543296725183664748 = 22;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_3543296725183664750 = 23;
        public const uint Internal_0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788 = 24;
        public const uint Internal_0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101 = 25;
        public const uint Internal_362fd1a7edeb85c48bb39119604133c5_7385481098666009946 = 26;
        public const uint Internal_362fd1a7edeb85c48bb39119604133c5_7385481098666009951 = 27;
        public const uint Internal_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761 = 28;
        public const uint Internal_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762 = 29;
        public const uint Internal_76ed9974a395ce54087bcb395f26407a_6959148627032638732 = 30;
        public const uint Internal_76ed9974a395ce54087bcb395f26407a_6959148627032638734 = 31;
        public const uint Internal_e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893 = 32;
        public const uint Internal_e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462 = 33;
        public const uint Internal_ff0eb699ebf32684891c45f672adc3ae_7001076288282754374 = 34;
        public const uint Internal_ff0eb699ebf32684891c45f672adc3ae_8801456816483979748 = 35;
        public const uint InternalAuthorityRequest = 0;
        public const uint InternalAuthorityTransfer = 1;
        public const uint InternalQuerySynced = 2;
        public const uint InternalAdoptOrphan = 3;
        public const uint InternalPersistenceReady = 4;
        public const uint InternalSceneIndexChanged = 5;
        public const uint Internal_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 = 6;
        public const uint Internal_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0 = 7;
        public const uint Internal_006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398 = 8;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb = 9;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2 = 10;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af = 11;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7 = 12;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f = 13;
        public const uint Internal_090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12 = 14;
        public const uint Internal_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708 = 15;
        public const uint Internal_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39 = 16;
        public const uint Internal_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1 = 17;
        public const uint Internal_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092 = 18;
        public const uint Internal_4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73 = 19;
        public const uint Internal_4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b = 20;
        public const uint Internal_4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44 = 21;
        public const uint Internal_8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569 = 22;
        public const uint Internal_ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847 = 23;

        private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>()
        {
            { 0, "WorldPosition" },
            { 1, "WorldOrientation" },
            { 2, "LocalUserComponent" },
            { 3, "WorldPositionQuery" },
            { 4, "ArchetypeComponent" },
            { 5, "Persistence" },
            { 6, "ConnectedEntity" },
            { 7, "UniqueID" },
            { 8, "Connection" },
            { 9, "ConnectionScene" },
            { 10, "Global" },
            { 11, "GlobalQuery" },
            { 12, "Tag" },
            { 13, "TagQuery" },
            { 14, "PreserveChildren" },
            { 15, "Scene" },
            { 16, "AssetId" },
            { 17, "GenericScale" },
            { 18, "_002e0f0727244a041abfd9d124ef5bce_3087197899905382071" },
            { 19, "_002e0f0727244a041abfd9d124ef5bce_3087197899905382075" },
            { 20, "_006c748d7f8085f4691d554734b27fe0_8362810714748207749" },
            { 21, "_006c748d7f8085f4691d554734b27fe0_8445149378463969736" },
            { 22, "_090aa92f766769348b4882a9d6b148e2_3543296725183664748" },
            { 23, "_090aa92f766769348b4882a9d6b148e2_3543296725183664750" },
            { 24, "_0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788" },
            { 25, "_0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101" },
            { 26, "_362fd1a7edeb85c48bb39119604133c5_7385481098666009946" },
            { 27, "_362fd1a7edeb85c48bb39119604133c5_7385481098666009951" },
            { 28, "_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761" },
            { 29, "_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762" },
            { 30, "_76ed9974a395ce54087bcb395f26407a_6959148627032638732" },
            { 31, "_76ed9974a395ce54087bcb395f26407a_6959148627032638734" },
            { 32, "_e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893" },
            { 33, "_e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462" },
            { 34, "_ff0eb699ebf32684891c45f672adc3ae_7001076288282754374" },
            { 35, "_ff0eb699ebf32684891c45f672adc3ae_8801456816483979748" },
        };

        public static string ComponentNameForTypeId(uint typeId)
        {
            if (componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
            {
                return componentName;
            }
            else
            {
                return "";
            }
        }

        public static readonly Dictionary<uint, MessageTarget> CommandRoutingByType = new Dictionary<uint, MessageTarget>()
        {
            { Definition.InternalAuthorityRequest , MessageTarget.All },
            { Definition.InternalAuthorityTransfer , MessageTarget.All },
            { Definition.InternalQuerySynced , MessageTarget.All },
            { Definition.InternalAdoptOrphan , MessageTarget.All },
            { Definition.InternalPersistenceReady , MessageTarget.All },
            { Definition.InternalSceneIndexChanged , MessageTarget.All },
            { Definition.Internal_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64 , MessageTarget.All },
            { Definition.Internal_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0 , MessageTarget.All },
            { Definition.Internal_006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398 , MessageTarget.All },
            { Definition.Internal_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb , MessageTarget.All },
            { Definition.Internal_090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2 , MessageTarget.All },
            { Definition.Internal_090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af , MessageTarget.All },
            { Definition.Internal_090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7 , MessageTarget.All },
            { Definition.Internal_090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f , MessageTarget.All },
            { Definition.Internal_090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12 , MessageTarget.All },
            { Definition.Internal_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708 , MessageTarget.All },
            { Definition.Internal_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39 , MessageTarget.All },
            { Definition.Internal_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1 , MessageTarget.All },
            { Definition.Internal_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092 , MessageTarget.All },
            { Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73 , MessageTarget.All },
            { Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b , MessageTarget.All },
            { Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44 , MessageTarget.All },
            { Definition.Internal_8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569 , MessageTarget.All },
            { Definition.Internal_ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847 , MessageTarget.All },
        };

        public ICoherenceComponentData ReadComponentUpdate(uint componentType, AbsoluteSimulationFrame referenceSimulationFrame,
            IInBitStream bitStream, Logger logger)
        {
            var inProtocolStream = new InProtocolBitStream(bitStream);

            switch (componentType)
            {
                case InternalWorldPosition:
                    return WorldPosition.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldOrientation:
                    return WorldOrientation.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPersistence:
                    return Persistence.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectedEntity:
                    return ConnectedEntity.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalUniqueID:
                    return UniqueID.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnection:
                    return Connection.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectionScene:
                    return ConnectionScene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobal:
                    return Global.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobalQuery:
                    return GlobalQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTag:
                    return Tag.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTagQuery:
                    return TagQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPreserveChildren:
                    return PreserveChildren.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalScene:
                    return Scene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalAssetId:
                    return AssetId.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGenericScale:
                    return GenericScale.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_002e0f0727244a041abfd9d124ef5bce_3087197899905382071:
                    return _002e0f0727244a041abfd9d124ef5bce_3087197899905382071.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_002e0f0727244a041abfd9d124ef5bce_3087197899905382075:
                    return _002e0f0727244a041abfd9d124ef5bce_3087197899905382075.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_006c748d7f8085f4691d554734b27fe0_8362810714748207749:
                    return _006c748d7f8085f4691d554734b27fe0_8362810714748207749.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_006c748d7f8085f4691d554734b27fe0_8445149378463969736:
                    return _006c748d7f8085f4691d554734b27fe0_8445149378463969736.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_090aa92f766769348b4882a9d6b148e2_3543296725183664748:
                    return _090aa92f766769348b4882a9d6b148e2_3543296725183664748.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_090aa92f766769348b4882a9d6b148e2_3543296725183664750:
                    return _090aa92f766769348b4882a9d6b148e2_3543296725183664750.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788:
                    return _0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101:
                    return _0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_362fd1a7edeb85c48bb39119604133c5_7385481098666009946:
                    return _362fd1a7edeb85c48bb39119604133c5_7385481098666009946.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_362fd1a7edeb85c48bb39119604133c5_7385481098666009951:
                    return _362fd1a7edeb85c48bb39119604133c5_7385481098666009951.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_76ed9974a395ce54087bcb395f26407a_6959148627032638732:
                    return _76ed9974a395ce54087bcb395f26407a_6959148627032638732.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_76ed9974a395ce54087bcb395f26407a_6959148627032638734:
                    return _76ed9974a395ce54087bcb395f26407a_6959148627032638734.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893:
                    return _e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462:
                    return _e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_ff0eb699ebf32684891c45f672adc3ae_7001076288282754374:
                    return _ff0eb699ebf32684891c45f672adc3ae_7001076288282754374.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_ff0eb699ebf32684891c45f672adc3ae_8801456816483979748:
                    return _ff0eb699ebf32684891c45f672adc3ae_8801456816483979748.Deserialize(referenceSimulationFrame, inProtocolStream);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(componentType),
                        $"Missing serialization implementation for a component: {componentType}");
            }
        }

        public uint WriteComponentUpdate(ICoherenceComponentData data, uint serializeAs, bool isRefSimFrameValid,
            AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream protocolStream, Logger logger)
        {
            switch (serializeAs)
            {
                case InternalWorldPosition:
                    return WorldPosition.Serialize((WorldPosition)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldOrientation:
                    return WorldOrientation.Serialize((WorldOrientation)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Serialize((LocalUserComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Serialize((WorldPositionQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Serialize((ArchetypeComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPersistence:
                    return Persistence.Serialize((Persistence)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectedEntity:
                    return ConnectedEntity.Serialize((ConnectedEntity)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalUniqueID:
                    return UniqueID.Serialize((UniqueID)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnection:
                    return Connection.Serialize((Connection)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectionScene:
                    return ConnectionScene.Serialize((ConnectionScene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobal:
                    return Global.Serialize((Global)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobalQuery:
                    return GlobalQuery.Serialize((GlobalQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTag:
                    return Tag.Serialize((Tag)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTagQuery:
                    return TagQuery.Serialize((TagQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPreserveChildren:
                    return PreserveChildren.Serialize((PreserveChildren)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalScene:
                    return Scene.Serialize((Scene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalAssetId:
                    return AssetId.Serialize((AssetId)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGenericScale:
                    return GenericScale.Serialize((GenericScale)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_002e0f0727244a041abfd9d124ef5bce_3087197899905382071:
                    return _002e0f0727244a041abfd9d124ef5bce_3087197899905382071.Serialize((_002e0f0727244a041abfd9d124ef5bce_3087197899905382071)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_002e0f0727244a041abfd9d124ef5bce_3087197899905382075:
                    return _002e0f0727244a041abfd9d124ef5bce_3087197899905382075.Serialize((_002e0f0727244a041abfd9d124ef5bce_3087197899905382075)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_006c748d7f8085f4691d554734b27fe0_8362810714748207749:
                    return _006c748d7f8085f4691d554734b27fe0_8362810714748207749.Serialize((_006c748d7f8085f4691d554734b27fe0_8362810714748207749)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_006c748d7f8085f4691d554734b27fe0_8445149378463969736:
                    return _006c748d7f8085f4691d554734b27fe0_8445149378463969736.Serialize((_006c748d7f8085f4691d554734b27fe0_8445149378463969736)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_090aa92f766769348b4882a9d6b148e2_3543296725183664748:
                    return _090aa92f766769348b4882a9d6b148e2_3543296725183664748.Serialize((_090aa92f766769348b4882a9d6b148e2_3543296725183664748)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_090aa92f766769348b4882a9d6b148e2_3543296725183664750:
                    return _090aa92f766769348b4882a9d6b148e2_3543296725183664750.Serialize((_090aa92f766769348b4882a9d6b148e2_3543296725183664750)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788:
                    return _0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788.Serialize((_0d0b3f2e44c5edc4c99c0a57d5674ec4_3938401364376064788)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101:
                    return _0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101.Serialize((_0d0b3f2e44c5edc4c99c0a57d5674ec4_5433512961855453101)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_362fd1a7edeb85c48bb39119604133c5_7385481098666009946:
                    return _362fd1a7edeb85c48bb39119604133c5_7385481098666009946.Serialize((_362fd1a7edeb85c48bb39119604133c5_7385481098666009946)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_362fd1a7edeb85c48bb39119604133c5_7385481098666009951:
                    return _362fd1a7edeb85c48bb39119604133c5_7385481098666009951.Serialize((_362fd1a7edeb85c48bb39119604133c5_7385481098666009951)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761.Serialize((_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885761)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762.Serialize((_4d7f86b504afd6f419f3d65f80c82f8f_3136628078399885762)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_76ed9974a395ce54087bcb395f26407a_6959148627032638732:
                    return _76ed9974a395ce54087bcb395f26407a_6959148627032638732.Serialize((_76ed9974a395ce54087bcb395f26407a_6959148627032638732)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_76ed9974a395ce54087bcb395f26407a_6959148627032638734:
                    return _76ed9974a395ce54087bcb395f26407a_6959148627032638734.Serialize((_76ed9974a395ce54087bcb395f26407a_6959148627032638734)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893:
                    return _e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893.Serialize((_e4bb2c0a78594ec42b6f43fae72c7a33_7251299098702113893)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462:
                    return _e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462.Serialize((_e4bb2c0a78594ec42b6f43fae72c7a33_7552079822175223462)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_ff0eb699ebf32684891c45f672adc3ae_7001076288282754374:
                    return _ff0eb699ebf32684891c45f672adc3ae_7001076288282754374.Serialize((_ff0eb699ebf32684891c45f672adc3ae_7001076288282754374)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_ff0eb699ebf32684891c45f672adc3ae_8801456816483979748:
                    return _ff0eb699ebf32684891c45f672adc3ae_8801456816483979748.Serialize((_ff0eb699ebf32684891c45f672adc3ae_8801456816483979748)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingComponentImplementation, ("component", data.GetComponentType()));
                    return 0;
            }
        }

        private IEntityCommand ReadCommand(uint commandType, Entity entity, MessageTarget target, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    return AuthorityRequest.Deserialize(bitStream, entity, target);
                case Definition.InternalAuthorityTransfer:
                    return AuthorityTransfer.Deserialize(bitStream, entity, target);
                case Definition.InternalQuerySynced:
                    return QuerySynced.Deserialize(bitStream, entity, target);
                case Definition.InternalAdoptOrphan:
                    return AdoptOrphan.Deserialize(bitStream, entity, target);
                case Definition.InternalPersistenceReady:
                    return PersistenceReady.Deserialize(bitStream, entity, target);
                case Definition.InternalSceneIndexChanged:
                    return SceneIndexChanged.Deserialize(bitStream, entity, target);
                case Definition.Internal_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64:
                    return _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64.Deserialize(bitStream, entity, target);
                case Definition.Internal_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0:
                    return _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0.Deserialize(bitStream, entity, target);
                case Definition.Internal_006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398:
                    return _006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398.Deserialize(bitStream, entity, target);
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb:
                    return _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb.Deserialize(bitStream, entity, target);
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2:
                    return _090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2.Deserialize(bitStream, entity, target);
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af:
                    return _090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af.Deserialize(bitStream, entity, target);
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7:
                    return _090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7.Deserialize(bitStream, entity, target);
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f:
                    return _090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f.Deserialize(bitStream, entity, target);
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12:
                    return _090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12.Deserialize(bitStream, entity, target);
                case Definition.Internal_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708:
                    return _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708.Deserialize(bitStream, entity, target);
                case Definition.Internal_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39:
                    return _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39.Deserialize(bitStream, entity, target);
                case Definition.Internal_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1:
                    return _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1.Deserialize(bitStream, entity, target);
                case Definition.Internal_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092:
                    return _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092.Deserialize(bitStream, entity, target);
                case Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73.Deserialize(bitStream, entity, target);
                case Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b.Deserialize(bitStream, entity, target);
                case Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44:
                    return _4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44.Deserialize(bitStream, entity, target);
                case Definition.Internal_8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569:
                    return _8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569.Deserialize(bitStream, entity, target);
                case Definition.Internal_ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847:
                    return _ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847.Deserialize(bitStream, entity, target);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(commandType),
                        $"Missing serialization implementation for a command: {commandType}");
            }
        }

        private IEntityInput ReadInput(uint inputType, Entity entity, long frame, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (inputType)
            {
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(inputType),
                        $"Missing serialization implementation for an input: {inputType}");
            }
        }

        public IEntityCommand[]	ReadCommands(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var commandData = new IEntityCommand[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                commandData[i] = ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
            }

            return commandData;
        }

        public IEntityInput[] ReadInputs(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var inputData = new IEntityInput[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var routing = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                var frame = (long)bitStream.ReadUint64();
                var input = ReadInput(componentType, entityID, frame, inBitStream, logger);
                input.Routing = routing;
                inputData[i] = input;
            }

            return inputData;
        }

        public IEntityCommand ReadCommand(IInBitStream bitStream, Logger logger)
        {
            var entityID = DeserializerTools.DeserializeEntity(bitStream);
            var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
            var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
            var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);

            return ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
        }

        public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
                    break;
                case Definition.InternalAuthorityTransfer:
                    AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
                    break;
                case Definition.InternalQuerySynced:
                    QuerySynced.Serialize((QuerySynced)data, bitStream);
                    break;
                case Definition.InternalAdoptOrphan:
                    AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
                    break;
                case Definition.InternalPersistenceReady:
                    PersistenceReady.Serialize((PersistenceReady)data, bitStream);
                    break;
                case Definition.InternalSceneIndexChanged:
                    SceneIndexChanged.Serialize((SceneIndexChanged)data, bitStream);
                    break;
                case Definition.Internal_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64:
                    _006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64.Serialize((_006c748d7f8085f4691d554734b27fe0_1ed269a9290d485ab7ad3dc6dd3b4b64)data, bitStream);
                    break;
                case Definition.Internal_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0:
                    _006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0.Serialize((_006c748d7f8085f4691d554734b27fe0_c71970d4b58a42738f53e2cd22aee1c0)data, bitStream);
                    break;
                case Definition.Internal_006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398:
                    _006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398.Serialize((_006c748d7f8085f4691d554734b27fe0_dc3e6bab0e3843059bb6679b058fe398)data, bitStream);
                    break;
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb:
                    _090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb.Serialize((_090aa92f766769348b4882a9d6b148e2_12cec6b3650e4d99b1275cda9ef317eb)data, bitStream);
                    break;
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2:
                    _090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2.Serialize((_090aa92f766769348b4882a9d6b148e2_738c73e4710e44b4bc915802f2893ed2)data, bitStream);
                    break;
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af:
                    _090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af.Serialize((_090aa92f766769348b4882a9d6b148e2_81d513233d084654aae421f25e4042af)data, bitStream);
                    break;
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7:
                    _090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7.Serialize((_090aa92f766769348b4882a9d6b148e2_9a46fadb59054bedb676fac4c0a5fbc7)data, bitStream);
                    break;
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f:
                    _090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f.Serialize((_090aa92f766769348b4882a9d6b148e2_b931ee7092e449b09ff7fa62d5a2588f)data, bitStream);
                    break;
                case Definition.Internal_090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12:
                    _090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12.Serialize((_090aa92f766769348b4882a9d6b148e2_c135117e48634d00b5179bf0ab62dc12)data, bitStream);
                    break;
                case Definition.Internal_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708:
                    _362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708.Serialize((_362fd1a7edeb85c48bb39119604133c5_33c865cdc8d14dcf82e779420dab9708)data, bitStream);
                    break;
                case Definition.Internal_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39:
                    _362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39.Serialize((_362fd1a7edeb85c48bb39119604133c5_5f7ece0daa0c4c91a021a802c3f47f39)data, bitStream);
                    break;
                case Definition.Internal_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1:
                    _362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1.Serialize((_362fd1a7edeb85c48bb39119604133c5_a385adf88dc64bb493660ec8bcbed6d1)data, bitStream);
                    break;
                case Definition.Internal_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092:
                    _4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092.Serialize((_4452a7764deb5654580ba23565e59e56_05c87585ce1a4602823f38746d382092)data, bitStream);
                    break;
                case Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73:
                    _4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73.Serialize((_4d7f86b504afd6f419f3d65f80c82f8f_6017b84d51184667b22990811e41ee73)data, bitStream);
                    break;
                case Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b:
                    _4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b.Serialize((_4d7f86b504afd6f419f3d65f80c82f8f_b7ee62b473624ec186543acb8b879c5b)data, bitStream);
                    break;
                case Definition.Internal_4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44:
                    _4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44.Serialize((_4d7f86b504afd6f419f3d65f80c82f8f_d14b47d79b424ee1a065ca3924190c44)data, bitStream);
                    break;
                case Definition.Internal_8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569:
                    _8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569.Serialize((_8b463149d5f8b1c4dab027c2c3ec2ad2_19099d1fae894e0c8fff3ff89dde0569)data, bitStream);
                    break;
                case Definition.Internal_ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847:
                    _ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847.Serialize((_ff0eb699ebf32684891c45f672adc3ae_658f49f164494f099ca2780d21d0a847)data, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingCommandImplementation, ("command", commandType));
                    break;
            }
        }

        public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
        {
            var inputData = (InputData)data;
            bitStream.WriteLong(inputData.Frame);

            switch (inputType)
            {
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingInputImplementation, ("input", inputType));
                    break;
            }
        }

        public IEntityCommand CreateAuthorityRequest(Entity entity, ClientID requester, AuthorityType authType)
        {
            return new AuthorityRequest(entity, (uint)requester, (int)authType);
        }

        public IEntityCommand CreateAdoptOrphanCommand()
        {
            return new AdoptOrphan();
        }

        public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand,
            out ClientID requester, out AuthorityType authType)
        {
            if (entityCommand is AuthorityRequest request)
            {
                requester = (ClientID)request.requester;
                authType = (AuthorityType)request.authorityType;

                return true;
            }

            requester = default;
            authType = default;

            return false;
        }

        public IEntityCommand CreateAuthorityTransfer(Entity entity, ClientID newAuthority, bool accepted, AuthorityType authType)
        {
            return new AuthorityTransfer(entity, (uint)newAuthority, accepted, (int)authType);
        }

        public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
            out bool transferAccepted, out AuthorityType authType)
        {
            if (entityCommand is AuthorityTransfer transfer)
            {
                newAuthority = (ClientID)transfer.newAuthority;
                transferAccepted = transfer.accepted;
                authType = (AuthorityType)transfer.authorityType;

                return true;
            }

            newAuthority = default;
            transferAccepted = default;
            authType = default;

            return false;
        }

        public ICoherenceComponentData GeneratePersistenceData()
        {
            var persistence = new Persistence();

            return persistence;
        }

        public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid, AbsoluteSimulationFrame simFrame)
        {
            var uniqueID = new UniqueID();
            uniqueID.uuid = uuid;
            uniqueID.uuidSimulationFrame = simFrame;
            uniqueID.FieldsMask = 0b1;

            return uniqueID;
        }

        public ICoherenceComponentData CreateGlobalComponent()
        {
            return new Global();
        }

        public ICoherenceComponentData GenerateGlobalQueryComponent()
        {
            return new GlobalQuery();
        }

        public string ExtractCoherenceUUID(ICoherenceComponentData data)
        {
            var uniqueID = (UniqueID)data;
            return uniqueID.uuid;
        }

        public bool IsConnectedEntity(ICoherenceComponentData data)
        {
            return data.GetComponentType() == Definition.InternalConnectedEntity;
        }

        public Entity ExtractConnectedEntityID(ICoherenceComponentData data)
        {
            var connectedEntity = (ConnectedEntity)data;

            return connectedEntity.value;
        }

        public string ExtractCoherenceTag(ICoherenceComponentData data)
        {
            var tag = (Tag)data;
            return tag.tag;
        }

        public bool TryGetSceneIndexChangedCommand(IEntityCommand entityCommand, out int sceneIndex)
        {
            if (entityCommand is SceneIndexChanged changed)
            {
                sceneIndex = (int)changed.sceneIndex;

                return true;
            }

            sceneIndex = default;

            return false;
        }

        public IEntityCommand CreateSceneIndexChangedCommand(Entity entity, int sceneIndex)
        {
            return new SceneIndexChanged(entity, sceneIndex);
        }

        public bool IsSendOrderedComponent(uint componentID)
        {
            switch(componentID)
            {
                case 6:
                    return true;
                default:
                    return false;
            }
        }
}


}
